//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisaTeaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaLamViec
    {
        public int MaCa { get; set; }
        public int MaNV { get; set; }
        public System.DateTime GioBatDau { get; set; }
        public Nullable<System.DateTime> GioKetThuc { get; set; }
        public Nullable<decimal> TongGio { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
