//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisaTeaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietLuong
    {
        public int MaChiTiet { get; set; }
        public int MaBangLuong { get; set; }
        public int MaNV { get; set; }
        public Nullable<decimal> TongGioLam { get; set; }
        public Nullable<decimal> GioTangCa { get; set; }
        public Nullable<decimal> TongLuong { get; set; }
    
        public virtual BangLuong BangLuong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
