//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisaTeaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietTopping
    {
        public int ID { get; set; }
        public int MaChiTietDon { get; set; }
        public int MaTop { get; set; }
    
        public virtual ChiTietDonHang ChiTietDonHang { get; set; }
        public virtual Topping Topping { get; set; }
    }
}
