//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisaTeaPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
    
        public int MaDon { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string HinhThucTT { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> MaKM { get; set; }
        public Nullable<decimal> SoTienGiam { get; set; }
        public string NguonDon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
    }
}
